version: "3.9"
services:
{{range $zone := .Zones}}
  {{$zone.ID}}:
    container_name: {{$zone.ID}}
    build:
      dockerfile: dockerfiles/Dockerfile_{{$zone.Implementation.Name}}
      args:
        VERSION: {{$zone.Implementation.Version}}
    volumes:
      - type: bind
        source: db.root
        target: /etc/bind/db.root
      - type: bind
        source: {{$zone.ID}}/config/
        target: {{$zone.Implementation.ConfigTarget}}
      - type: bind
        source: zones
        target: /zones
      - type: bind
        source: {{$zone.ID}}/logs
        target: {{$zone.Implementation.LogsTarget}}
    networks:
      dns-testbed:
        ipv4_address: {{$zone.IP}}
    cap_add:
      - NET_ADMIN
    command:
      - /bin/sh
      - -c
      - |
      {{range $cmd := $zone.Implementation.StartCommands}}
        {{$cmd}}
      {{end}}
        tc qdisc add dev eth0 root netem delay 0ms
        tail -F anything
{{end}}
  
{{range $resolver := .Resolvers}}
  {{$resolver.ID}}:
    container_name: {{$resolver.ID}}
    build:
      dockerfile: dockerfiles/Dockerfile_{{$resolver.Implementation.Name}}
      args:
        VERSION: {{$resolver.Implementation.Version}}
    volumes:
      - type: bind
        source: {{$resolver.ID}}/config
        target: {{$resolver.Implementation.ConfigTarget}}
      - type: bind
        source: db.root
        target: {{$resolver.Implementation.RootHintsTarget}}
      - type: bind
        source: {{$resolver.ID}}/logs
        target: {{$resolver.Implementation.LogsTarget}}
    networks:
      dns-testbed:
        ipv4_address: {{$resolver.IP}}
    command:
      - /bin/sh
      - -c
      - |
      {{range $cmd := $resolver.Implementation.StartCommands}}
        {{$cmd}}
      {{end}}
        tail -F anything
{{end}}

  {{.Client.ID}}:
    container_name: {{.Client.ID}}
    image: jodokvieli/client
    volumes:
      - type: bind
        source: {{.Client.ID}}/resolv.conf
        target: /etc/resolv.conf
    networks:
      dns-testbed:
        ipv4_address: {{.Client.IP}}
    command:
      - /bin/sh
      - -c
      - |
        tail -F anything
networks:
  dns-testbed:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1