FROM ubuntu:bionic

RUN apt-get update \
    && apt-get install -y \
    vim \
    wget \
    tar \
    flex \
    bison \
    libexpat1-dev \
    libssl-dev \
    build-essential

RUN apt-get install -y \
    libuv1-dev \
    libnghttp2-dev \
    libcap-dev \
    libprotobuf-c-dev libprotobuf-c1 \
    protobuf-c-compiler \
    fstrm-bin libfstrm0 libfstrm-dev \
    libprotobuf-c-dev libprotobuf-c1

RUN wget https://www.nlnetlabs.nl/downloads/unbound/unbound-1.10.0.tar.gz
RUN tar xzf unbound-1.10.0.tar.gz
WORKDIR unbound-1.10.0
RUN ./configure --enable-dnstap
RUN make
RUN make install

# Run eternal loop
CMD ["/bin/bash", "-c", "while :; do sleep 10; done"]