version: "3.9"
services:
  root:
    container_name: root
    build: nameserver
    volumes:
      - type: bind
        source: nameserver/db.root
        target: /etc/bind/db.root
      - type: bind
        source: nameserver/named.conf.options
        target: /etc/bind/named.conf.options
      - type: bind
        source: nameserver/root/named.conf.local
        target: /etc/bind/named.conf.local
      - type: bind
        source: nameserver/root/zones
        target: /etc/zones
      - type: bind
        source: nameserver/root/logs
        target: /etc/logs
    networks:
      dns-testbed:
        ipv4_address: 172.20.0.2
    cap_add:
      - NET_ADMIN
    command:
      - /bin/sh
      - -c
      - |
        service bind9 start
        tc qdisc add dev eth0 root netem delay 0ms
        tail -F anything
  com:
    container_name: com
    build: nameserver
    volumes:
      - type: bind
        source: nameserver/db.root
        target: /etc/bind/db.root
      - type: bind
        source: nameserver/named.conf.options
        target: /etc/bind/named.conf.options
      - type: bind
        source: nameserver/com/named.conf.local
        target: /etc/bind/named.conf.local
      - type: bind
        source: nameserver/com/zones
        target: /etc/zones
      - type: bind
        source: nameserver/com/logs
        target: /etc/logs
    networks:
      dns-testbed:
        ipv4_address: 172.20.0.3
    cap_add:
      - NET_ADMIN
    command:
      - /bin/sh
      - -c
      - |
        service bind9 start
        tc qdisc add dev eth0 root netem delay 0ms
        tail -F anything
  net:
    container_name: net
    build: nameserver
    volumes:
      - type: bind
        source: nameserver/db.root
        target: /etc/bind/db.root
      - type: bind
        source: nameserver/named.conf.options
        target: /etc/bind/named.conf.options
      - type: bind
        source: nameserver/net/named.conf.local
        target: /etc/bind/named.conf.local
      - type: bind
        source: nameserver/net/zones
        target: /etc/zones
      - type: bind
        source: nameserver/net/logs
        target: /etc/logs
    cap_add:
      - NET_ADMIN
    networks:
      dns-testbed:
        ipv4_address: 172.20.0.4
    command:
      - /bin/sh
      - -c
      - |
        service bind9 start
        tc qdisc add dev eth0 root netem delay 0ms
        tail -F anything
  target-com:
    container_name: target-com
    build: nameserver
    volumes:
      - type: bind
        source: nameserver/db.root
        target: /etc/bind/db.root
      - type: bind
        source: nameserver/named.conf.options
        target: /etc/bind/named.conf.options
      - type: bind
        source: nameserver/target-com/named.conf.local
        target: /etc/bind/named.conf.local
      - type: bind
        source: nameserver/target-com/zones
        target: /etc/zones
      - type: bind
        source: nameserver/target-com/logs
        target: /etc/logs
    networks:
      dns-testbed:
        ipv4_address: 172.20.0.5
    cap_add:
      - NET_ADMIN
    command:
      - /bin/sh
      - -c
      - |
        service bind9 start
        tc qdisc add dev eth0 root netem delay 0ms
        tail -F anything
  inter-net:
    container_name: inter-net
    build: nameserver
    volumes:
      - type: bind
        source: nameserver/db.root
        target: /etc/bind/db.root
      - type: bind
        source: nameserver/named.conf.options
        target: /etc/bind/named.conf.options
      - type: bind
        source: nameserver/inter-net/named.conf.local
        target: /etc/bind/named.conf.local
      - type: bind
        source: nameserver/inter-net/zones
        target: /etc/zones
      - type: bind
        source: nameserver/inter-net/logs
        target: /etc/logs
    networks:
      dns-testbed:
        ipv4_address: 172.20.0.6
    cap_add:
      - NET_ADMIN
    command:
      - /bin/sh
      - -c
      - |
        service bind9 start
        tc qdisc add dev eth0 root netem delay 0ms
        tail -F anything
  resolver-bind9:
    container_name: resolver-bind-9.11.3
    build: resolver/bind9
    volumes:
      - type: bind
        source: resolver/bind9/named.conf.options
        target: /etc/bind/named.conf.options
      - type: bind
        source: resolver/db.root
        target: /etc/bind/db.root
      - type: bind
        source: resolver/bind9/logs
        target: /etc/logs
    networks:
      dns-testbed:
        ipv4_address: 172.20.0.10
    command:
      - /bin/sh
      - -c
      - |
        service bind9 start
        tc qdisc add dev eth0 root netem delay 0ms
        tail -F anything
  resolver-unbound-1.17.0:
    container_name: resolver-unbound-1.17.0
    build: resolver/unbound-1.17.0
    volumes:
      - type: bind
        source: resolver/unbound-1.17.0/unbound.conf
        target: /usr/local/etc/unbound/unbound.conf
      - type: bind
        source: resolver/db.root
        target: /usr/local/etc/unbound/db.root
      - type: bind
        source: resolver/unbound-1.17.0/logs
        target: /usr/local/etc/logs
    networks:
      dns-testbed:
        ipv4_address: 172.20.0.11
    command:
      - /bin/sh
      - -c
      - |
        unbound-control-setup
        unbound-control start
        tail -F anything
  resolver-unbound-1.16.0:
    container_name: resolver-unbound-1.16.0
    build: resolver/unbound-1.16.0
    volumes:
      - type: bind
        source: resolver/unbound-1.16.0/unbound.conf
        target: /usr/local/etc/unbound/unbound.conf
      - type: bind
        source: resolver/db.root
        target: /usr/local/etc/unbound/db.root
      - type: bind
        source: resolver/unbound-1.16.0/logs
        target: /usr/local/etc/logs
    networks:
      dns-testbed:
        ipv4_address: 172.20.0.12
    command:
      - /bin/sh
      - -c
      - |
        unbound-control-setup
        unbound-control start
        tail -F anything
  resolver-unbound-1.10.0:
    container_name: resolver-unbound-1.10.0
    build: resolver/unbound-1.10.0
    volumes:
      - type: bind
        source: resolver/unbound-1.10.0/unbound.conf
        target: /usr/local/etc/unbound/unbound.conf
      - type: bind
        source: resolver/db.root
        target: /usr/local/etc/unbound/db.root
      - type: bind
        source: resolver/unbound-1.10.0/logs
        target: /usr/local/etc/logs
    networks:
      dns-testbed:
        ipv4_address: 172.20.0.13
    command:
      - /bin/sh
      - -c
      - |
        unbound-control-setup
        unbound-control start
        tail -F anything
  resolver-powerdns-4.7.3:
    container_name: resolver-powerDNS-4.7.3
    build: resolver/powerdns-4.7.3
    volumes:
      - type: bind
        source: resolver/powerdns-4.7.3/recursor.conf
        target: /etc/powerdns/recursor.conf
      - type: bind
        source: resolver/db.root
        target: /usr/share/dns/myroot.hints
    networks:
      dns-testbed:
        ipv4_address: 172.20.0.14
    command:
      - /bin/sh
      - -c
      - |
        /etc/init.d/pdns-recursor start
        tail -F anything
#  resolver-knot:
#    container_name: resolver-knot
#    image: cznic/knot-resolver
#    volumes:
#      - type: bind
#        source: resolver/knot/kresd.conf
#        target: /etc/knot-resolver/kresd.conf
#    networks:
#      dns-testbed:
#        ipv4_address: 172.20.0.15
#    entrypoint: /bin/bash -c
#    command:
#      - |
#        tail -F anything
  client:
    container_name: client
    build: client
    networks:
      dns-testbed:
        ipv4_address: 172.20.0.9
    command:
      - /bin/sh
      - -c
      - |
        tail -F anything
networks:
  dns-testbed:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1