
zones:
- qname: .
  ip: 172.20.0.2
- qname: com.
  ip: 172.20.0.3
- qname: net.
  ip: 172.20.0.4
- qname: target.com.
  ip: 172.20.0.5
- qname: inter.net.
  ip: 172.20.0.6

resolvers:
- implementation: bind
  version: 9.18.4
  ip: 172.20.0.51
- implementation: unbound
  version: 1.16.0
  ip: 172.20.0.52
- implementation: unbound
  version: 1.10.0
  ip: 172.20.0.53
- implementation: powerdns
  version: 4.7.3
  ip: 172.20.0.54

client:
  id: client
  ip: 172.20.0.99
  nameserver: 172.20.0.51
